spring:
  application:
    name: AGENCYSERVICE


  data:
    mongodb:
      uri: mongodb+srv://Shreyansh:Pass123@cluster0.hlz9zmj.mongodb.net/CarRentalSystem


server:
  port: 8082

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/