spring:
  application:
    name: AGENCYSERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI}
server:
  port: 8082

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/