
services:

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka:
    build: ./eureka
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      rabbitmq:
        condition: service_healthy

  gateway:
    build: ./Gateway
    container_name: gateway
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET_KEY=${JWT_SECRET_KEY2}
    depends_on:
      - eureka

  user-service:
    build: ./UserService
    container_name: user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JWT_SECRET_KEY=${JWT_SECRET_KEY2}
    depends_on:
      - eureka
      - mongodb

  agency-service:
    build: ./AgencyService
    container_name: agency-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - mongodb
      - redis

  booking-service:
    build: ./BookingService
    container_name: booking-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - mongodb
      - redis
      - rabbitmq

  payment-service:
    build: ./PaymentService
    container_name: payment-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - eureka
      - mongodb
      - rabbitmq

volumes:
  mongo_data: