spring:
  application:
    name: Gateway

  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: AGENCYSERVICE
          uri: lb://AGENCYSERVICE
          predicates:
            - Path=/api/agency/**
        - id: BOOKINGSERVICE
          uri: lb://BOOKINGSERVICE
          predicates:
              - Path=/api/bookings/**

server:
  port: 8090

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
