spring:
  application:
    name: USERSERVICE

  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/CarRentalSystem?authSource=admin

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8081

eureka:
  instance:
    hostname: user-service
    prefer-ip-address: true



jwt:
  secretKey: ${JWT_SECRET_KEY}