spring:
  application:
    name: USERSERVICE

  data:
    mongodb:
      uri: mongodb://root:root@mongodb:27017/CarRentalSystem?authSource=admin

server:
  port: 8081

eureka:
  instance:
    ip-address: user-service
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

jwt:
  secretKey: ${JWT_SECRET_KEY}