spring:
  application:
    name : AuthService

  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username : postgres.obfltxugtkkjupdvdiwa
    password : 8Yjfi2RjDZnVyhHh
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8087

jwt:
  secretKey: "ilumorhaehapermapoiergoigp8y9p58,,7yq9084y9389y9yp9huh3ui3i38"

eureka:
  instance:
    hostname: auth-service
    prefer-ip-address: true