spring:
  application:
    name: BOOKINGSERVICE

  cache:
    type: redis

  data:
    redis:
      host: redis-19625.crce295.us-east-1-1.ec2.cloud.redislabs.com
      port: 19625
      password: HcN77SiCvSfLv4tYY0CWd2QSRDXv0Iiu

    mongodb:
      uri: ${MONGODB_URI}

  #RabbitMq
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8083

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/