spring:
  application:
    name: BOOKINGSERVICE

  cache:
    type: redis

  data:
    redis:
      host: redis-11820.c12.us-east-1-4.ec2.cloud.redislabs.com
      port: 11820
      password: v9qLCQispgaIjurqYh7iii1tf34paxSM


    mongodb:
      uri: mongodb+srv://Shreyansh:Pass123@cluster0.hlz9zmj.mongodb.net/CarRentalSystem

server:
  port: 8083

eureka:
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/